// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-60sb3ev8ehRiEUvnqH5ZFLIKdFJRDQ',
    appId: '1:480485377144:web:01db6e546c9fe1b301198d',
    messagingSenderId: '480485377144',
    projectId: 'chatter-307c2',
    authDomain: 'chatter-307c2.firebaseapp.com',
    storageBucket: 'chatter-307c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8f0DXZ-f0OO3qasIS8FeyREtXhYSH_s',
    appId: '1:480485377144:android:c7a2fbeb44156b4301198d',
    messagingSenderId: '480485377144',
    projectId: 'chatter-307c2',
    storageBucket: 'chatter-307c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHv2VRx3i-_SQ8pxwI86tgVkVQlVM9yms',
    appId: '1:480485377144:ios:a057480fba43d3e101198d',
    messagingSenderId: '480485377144',
    projectId: 'chatter-307c2',
    storageBucket: 'chatter-307c2.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
